import photo1 from "../photo/images.jpg";
import photo2 from "../photo/images-1.jpg";
import photo3 from "../photo/images-2.jpg";
import photo4 from "../photo/images-3.jpg";
import photo5 from "../photo/download-2.jpg";
import photo6 from "../photo/download-3.jpg";
import photo7 from "../photo/download-4.jpg";
import photo8 from "../photo/download-5.jpg";
import photo9 from "../photo/download.jpg";
import photo10 from "../photo/download-1.jpg";

export const userCatalog = [
  {
    id: "hong-private",
    name: "홍길동",
    isPrivate: true,
    isFollowing: false,
    followingCount: 47,
    followerCount: 2,
    savedCount: 195,
    uploadCount: 21,
    savedMemeIds: ["trend-1", "trend-3", "rec-1", "rec-3"],
    uploadedMemeIds: ["trend-1", "trend-3", "trend-5", "trend-7"],
  },
  {
    id: "min-public",
    name: "김민서",
    isPrivate: false,
    isFollowing: true,
    followingCount: 47,
    followerCount: 2,
    savedCount: 195,
    uploadCount: 21,
    savedMemeIds: [
      "trend-2",
      "trend-4",
      "trend-6",
      "trend-8",
      "rec-2",
      "rec-4",
      "trend-1",
      "rec-1",
    ],
    uploadedMemeIds: ["trend-2", "trend-4", "trend-6", "trend-8"],
  },
];

export const userProfileMap = Object.fromEntries(
  userCatalog.map((profile) => [profile.id, profile])
);

export const memeCatalog = [
  {
    id: "trend-1",
    image: photo1,
    alt: "친구들과 함께 앉아 있는 인기 밈 이미지",
    title: "시험 끝난 날 단체로 놀러 가는 순간",
    likes: 2306,
    category: "학교",
    badge: "리믹스",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["이미지", "10대"],
    searchTags: ["시험", "친구", "단체", "놀러"],
    comments: [{ id: "trend-1-comment-1", author: "이름", text: "댓글글" }],
  },
  {
    id: "trend-2",
    image: photo2,
    alt: "서프라이즈 반응을 담은 인기 밈 이미지",
    title: "조별 과제 발표 직전 표정",
    likes: 1842,
    category: "학교",
    badge: "원본",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["gif", "20대"],
    searchTags: ["조별과제", "발표", "긴장", "학교"],
    comments: [{ id: "trend-2-comment-1", author: "민지", text: "진짜 이 상황 그 자체" }],
  },
  {
    id: "trend-3",
    image: photo3,
    alt: "황당한 상황을 담은 인기 밈 이미지",
    title: "교수님이 갑자기 팀 발표를 시킬 때",
    likes: 2014,
    category: "학교",
    badge: "리믹스",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["이미지", "30대"],
    searchTags: ["교수님", "팀발표", "당황", "학교"],
    comments: [{ id: "trend-3-comment-1", author: "지훈", text: "저도 저장했습니다" }],
  },
  {
    id: "trend-4",
    image: photo4,
    alt: "웃긴 상황을 담은 인기 밈 이미지",
    title: "과제 제출하고 나서 메신저 확인하는 나",
    likes: 1567,
    category: "학교",
    badge: "리믹스",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["gif", "10대"],
    searchTags: ["과제", "제출", "메신저", "학교"],
    comments: [{ id: "trend-4-comment-1", author: "서연", text: "완전 공감돼요" }],
  },
  {
    id: "trend-5",
    image: photo9,
    alt: "장난스러운 표정의 밈 이미지",
    title: "수업 듣다가 교수님이 갑자기 질문할 때",
    likes: 1940,
    category: "학교",
    badge: "원본",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["이미지", "20대"],
    searchTags: ["수업", "질문", "교수님", "학교"],
    comments: [{ id: "trend-5-comment-1", author: "지우", text: "딱 제 표정이에요" }],
  },
  {
    id: "trend-6",
    image: photo10,
    alt: "귀여운 캐릭터 밈 이미지",
    title: "친구가 과제 다 했냐고 물어볼 때",
    likes: 1678,
    category: "학교",
    badge: "리믹스",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["이미지", "30대"],
    searchTags: ["과제", "친구", "질문", "학교"],
    comments: [{ id: "trend-6-comment-1", author: "민석", text: "이 밈 너무 웃겨요" }],
  },
  {
    id: "trend-7",
    image: photo1,
    alt: "친구들과 함께 있는 추가 인기 밈 이미지",
    title: "시험 끝나고 단톡방 폭발하는 순간",
    likes: 2520,
    category: "학교",
    badge: "리믹스",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["gif", "10대"],
    searchTags: ["시험", "단톡방", "친구", "학교"],
    comments: [{ id: "trend-7-comment-1", author: "예진", text: "진짜 공감됩니다" }],
  },
  {
    id: "trend-8",
    image: photo3,
    alt: "당황한 표정의 추가 인기 밈 이미지",
    title: "출석 체크 끝난 줄 알았는데 다시 부를 때",
    likes: 1813,
    category: "학교",
    badge: "원본",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["이미지", "20대"],
    searchTags: ["출석", "체크", "당황", "학교"],
    comments: [{ id: "trend-8-comment-1", author: "현지", text: "바로 저장했어요" }],
  },
  {
    id: "rec-1",
    image: photo5,
    alt: "추천 밈 이미지 1",
    title: "친구가 갑자기 약속 취소했을 때",
    likes: 1734,
    category: "일상",
    badge: "원본",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["이미지", "10대"],
    searchTags: ["약속", "취소", "친구", "일상"],
    comments: [{ id: "rec-1-comment-1", author: "도윤", text: "이거 바로 저장" }],
  },
  {
    id: "rec-2",
    image: photo6,
    alt: "추천 밈 이미지 2",
    title: "퇴근 5분 전 새로운 일 들어왔을 때",
    likes: 2631,
    category: "직장",
    badge: "리믹스",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["gif", "30대"],
    searchTags: ["퇴근", "직장", "야근", "회사"],
    comments: [{ id: "rec-2-comment-1", author: "지민", text: "현실 고증 미쳤다" }],
  },
  {
    id: "rec-3",
    image: photo7,
    alt: "추천 밈 이미지 3",
    title: "택배 도착 문자를 본 순간",
    likes: 1498,
    category: "일상",
    badge: "원본",
    authorId: "hong-private",
    author: "홍길동",
    date: "날짜",
    fixedTags: ["이미지", "20대"],
    searchTags: ["택배", "문자", "도착", "일상"],
    comments: [{ id: "rec-3-comment-1", author: "예린", text: "이 표정 너무 잘 알죠" }],
  },
  {
    id: "rec-4",
    image: photo8,
    alt: "추천 밈 이미지 4",
    title: "월요일 아침 알람 끄고 다시 눕는 기분",
    likes: 2119,
    category: "일상",
    badge: "리믹스",
    authorId: "min-public",
    author: "김민서",
    date: "날짜",
    fixedTags: ["gif", "30대"],
    searchTags: ["월요일", "아침", "알람", "출근"],
    comments: [{ id: "rec-4-comment-1", author: "현우", text: "제 월요일입니다" }],
  },
];

export const trendingMemes = memeCatalog.slice(0, 8);
export const recommendedMemes = memeCatalog.slice(8, 12);

export function getMemeById(memeId) {
  return memeCatalog.find((meme) => meme.id === memeId);
}
